/**
 * Tailwind CSS Configuration
 * Generated by image-to-design-spec
 * Source: {{SOURCE_IMAGE}}
 * Date: {{TIMESTAMP}}
 */

module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          50: '{{PRIMARY_50}}',
          100: '{{PRIMARY_100}}',
          200: '{{PRIMARY_200}}',
          300: '{{PRIMARY_300}}',
          400: '{{PRIMARY_400}}',
          500: '{{PRIMARY_500}}',
          600: '{{PRIMARY_600}}',
          700: '{{PRIMARY_700}}',
          800: '{{PRIMARY_800}}',
          900: '{{PRIMARY_900}}',
          950: '{{PRIMARY_950}}',
        },
        secondary: {
          50: '{{SECONDARY_50}}',
          100: '{{SECONDARY_100}}',
          200: '{{SECONDARY_200}}',
          300: '{{SECONDARY_300}}',
          400: '{{SECONDARY_400}}',
          500: '{{SECONDARY_500}}',
          600: '{{SECONDARY_600}}',
          700: '{{SECONDARY_700}}',
          800: '{{SECONDARY_800}}',
          900: '{{SECONDARY_900}}',
          950: '{{SECONDARY_950}}',
        },
        accent: {
          50: '{{ACCENT_50}}',
          100: '{{ACCENT_100}}',
          200: '{{ACCENT_200}}',
          300: '{{ACCENT_300}}',
          400: '{{ACCENT_400}}',
          500: '{{ACCENT_500}}',
          600: '{{ACCENT_600}}',
          700: '{{ACCENT_700}}',
          800: '{{ACCENT_800}}',
          900: '{{ACCENT_900}}',
          950: '{{ACCENT_950}}',
        },
      },
      fontFamily: {
        heading: ['{{HEADING_FONT}}', 'sans-serif'],
        body: ['{{BODY_FONT}}', 'sans-serif'],
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'full': '9999px',
      },
    },
  },
};
